
// connexion avec l'email et le mot de passe
post http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}
###
// enregistrement d'un nouvel utilisateur
post http://localhost:3000/register 
Content-Type: application/json

{
  "email": "admin@admin.com",
    "password": "admin",
    "password_confirmation": "admin",
    "nom" : "admin",
    "prenom" : "admin"
}
###
// demande d'acces
post http://localhost:3000/ask
Content-Type: application/json

{
  "email": "admin@admin.com",
  "nom_complet": "admin admin",
  "fonction": "admin",
  "direction": "direction A",
  "justificatif": "justification de la demande"
}

