
// connexion avec l'email et le mot de passe
post http://localhost:3000/login
Content-Type: application/json

{
  "adresse_email": "admin@admin.com",
  "password": "admin"
}
###
// enregistrement d'un nouvel utilisateur
post http://localhost:3000/register 
Content-Type: application/json

{
    "adresse_email": "admin@admin.com",
    "password": "admin",
    "password_confirmation": "admin",
    "noms" : "admin",
    "prenoms" : "admin"
}
###
// demande d'acces
post http://localhost:3000/ask
Content-Type: application/json

{
  "adresse_email": "admin@admin.com",
  "fonction": "admin",
  "direction": "direction A",
  "justificatif": "justification de la demande"
}

